import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Archivo, Berkshire_Swash } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

const archivo = Archivo({
  variable: "--font-archivo",
  subsets: ["latin"],
});

const berkshireSwash = Berkshire_Swash({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-berkshireSwash",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" className="min-h-screen">
      <body
        className={`${archivo.variable} ${berkshireSwash.variable} antialiased flex flex-col min-h-screen`}
      >
        <Header />
        <main className="grow-1">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
